ALTER TABLE tabela_de_vendedores ADD COLUMN (DATA_ADMISSAO DATE, DE_FERIAS BIT);

INSERT INTO tabela_de_vendedores(
MATRICULA,
NOME,
PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS ) VALUES (
'00233', 'João Geraldo da Fonseca', 10, '2014-08-14', 0);
INSERT INTO tabela_de_vendedores(
MATRICULA,
NOME,
PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS) VALUES (
'00235', 'Márcio Almeida Silva', 8, '2013-09-17', 1);
INSERT INTO tabela_de_vendedores(
MATRICULA,
NOME,
PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS) VALUES (
'00236', 'Cláudia Morais', 8, '2017-03-18', 1);
INSERT INTO tabela_de_vendedores(
MATRICULA,
NOME,
PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS) VALUES (
'00238', 'Péricles Alves', 11, '2016-08-21', 0);